server:
  port: 8081
  error:
    include-message=always:
spring:
  application:
    name: user-service
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5433/Multree
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
  main:
    #    allow-bean-definition-overriding: true
    allow-circular-references: true


taken: email or username is taken by another user
insert: Data successfully stored in the database

#Key depends on jwt algorithm: If RSA => needs public, private; if HMAC => NEEDS ONLY single key....
app:
  jwt:
    secret: 432646294A404D635166546A576E5A7234753778214125442A472D4B6150645267556B58703273357638792F423F4528482B4D6251655468566D597133743677
    expiration-in-ms: 86400000

